# SonarQube Project Configuration
sonar.projectKey=ankitrout07_DevSecOps-Security-CI-CD
sonar.projectName=DevSecOps-Security-CI-CD
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src/app
sonar.language=js
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**, **/*.test.js, src/app/public/js/app.js

# Quality Gate requirements (optional but recommended)
sonar.qualitygate.wait=true
